spring.application.name=ecom-project

spring.datasource.url = jdbc:mysql://localhost:3306/ecom_project
spring.datasource.username = root
spring.datasource.password = 4922

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
