spring.application.name=springSecurity1

spring.security.user.name = anik
spring.security.user.password = anik

spring.datasource.url = jdbc:mysql://localhost:3306/spring_security
spring.datasource.username = root
spring.datasource.password = 4922
